export enum MySQLErrorCodes {
    CR_UNKNOWN_ERROR = "CR_UNKNOWN_ERROR",
    CR_SOCKET_CREATE_ERROR = "CR_SOCKET_CREATE_ERROR",
    CR_CONNECTION_ERROR = "CR_CONNECTION_ERROR",
    CR_CONN_HOST_ERROR = "CR_CONN_HOST_ERROR",
    CR_IPSOCK_ERROR = "CR_IPSOCK_ERROR",
    CR_UNKNOWN_HOST = "CR_UNKNOWN_HOST",
    CR_SERVER_GONE_ERROR = "CR_SERVER_GONE_ERROR",
    CR_VERSION_ERROR = "CR_VERSION_ERROR",
    ER_HASHCHK = "ER_HASHCHK",
    ER_NISAMCHK = "ER_NISAMCHK",
    ER_NO = "ER_NO",
    ER_YES = "ER_YES",
    ER_CANT_CREATE_FILE = "ER_CANT_CREATE_FILE",
    ER_CANT_CREATE_TABLE = "ER_CANT_CREATE_TABLE",
    ER_CANT_CREATE_DB = "ER_CANT_CREATE_DB",
    ER_DB_CREATE_EXISTS = "ER_DB_CREATE_EXISTS",
    ER_DB_DROP_EXISTS = "ER_DB_DROP_EXISTS",
    ER_DB_DROP_DELETE = "ER_DB_DROP_DELETE",
    ER_DB_DROP_RMDIR = "ER_DB_DROP_RMDIR",
    ER_CANT_DELETE_FILE = "ER_CANT_DELETE_FILE",
    ER_CANT_FIND_SYSTEM_REC = "ER_CANT_FIND_SYSTEM_REC",
    ER_CANT_GET_STAT = "ER_CANT_GET_STAT",
    ER_CANT_GET_WD = "ER_CANT_GET_WD",
    ER_CANT_LOCK = "ER_CANT_LOCK",
    ER_CANT_OPEN_FILE = "ER_CANT_OPEN_FILE",
    ER_FILE_NOT_FOUND = "ER_FILE_NOT_FOUND",
    ER_CANT_READ_DIR = "ER_CANT_READ_DIR",
    ER_CANT_SET_WD = "ER_CANT_SET_WD",
    ER_CHECKREAD = "ER_CHECKREAD",
    ER_DISK_FULL = "ER_DISK_FULL",
    ER_DUP_KEY = "ER_DUP_KEY",
    ER_ERROR_ON_CLOSE = "ER_ERROR_ON_CLOSE",
    ER_ERROR_ON_READ = "ER_ERROR_ON_READ",
    ER_ERROR_ON_RENAME = "ER_ERROR_ON_RENAME",
    ER_ERROR_ON_WRITE = "ER_ERROR_ON_WRITE",
    ER_FILE_USED = "ER_FILE_USED",
    ER_FILSORT_ABORT = "ER_FILSORT_ABORT",
    ER_FORM_NOT_FOUND = "ER_FORM_NOT_FOUND",
    ER_GET_ERRNO = "ER_GET_ERRNO",
    ER_ILLEGAL_HA = "ER_ILLEGAL_HA",
    ER_KEY_NOT_FOUND = "ER_KEY_NOT_FOUND",
    ER_NOT_FORM_FILE = "ER_NOT_FORM_FILE",
    ER_NOT_KEYFILE = "ER_NOT_KEYFILE",
    ER_OLD_KEYFILE = "ER_OLD_KEYFILE",
    ER_OPEN_AS_READONLY = "ER_OPEN_AS_READONLY",
    ER_OUTOFMEMORY = "ER_OUTOFMEMORY",
    ER_OUT_OF_SORTMEMORY = "ER_OUT_OF_SORTMEMORY",
    ER_UNEXPECTED_EOF = "ER_UNEXPECTED_EOF",
    ER_CON_COUNT_ERROR = "ER_CON_COUNT_ERROR",
    ER_OUT_OF_RESOURCES = "ER_OUT_OF_RESOURCES",
    ER_BAD_HOST_ERROR = "ER_BAD_HOST_ERROR",
    ER_HANDSHAKE_ERROR = "ER_HANDSHAKE_ERROR",
    ER_DBACCESS_DENIED_ERROR = "ER_DBACCESS_DENIED_ERROR",
    ER_ACCESS_DENIED_ERROR = "ER_ACCESS_DENIED_ERROR",
    ER_NO_DB_ERROR = "ER_NO_DB_ERROR",
    ER_UNKNOWN_COM_ERROR = "ER_UNKNOWN_COM_ERROR",
    ER_BAD_NULL_ERROR = "ER_BAD_NULL_ERROR",
    ER_BAD_DB_ERROR = "ER_BAD_DB_ERROR",
    ER_TABLE_EXISTS_ERROR = "ER_TABLE_EXISTS_ERROR",
    ER_BAD_TABLE_ERROR = "ER_BAD_TABLE_ERROR",
    ER_NON_UNIQ_ERROR = "ER_NON_UNIQ_ERROR",
    ER_SERVER_SHUTDOWN = "ER_SERVER_SHUTDOWN",
    ER_BAD_FIELD_ERROR = "ER_BAD_FIELD_ERROR",
    ER_WRONG_FIELD_WITH_GROUP = "ER_WRONG_FIELD_WITH_GROUP",
    ER_WRONG_GROUP_FIELD = "ER_WRONG_GROUP_FIELD",
    ER_WRONG_SUM_SELECT = "ER_WRONG_SUM_SELECT",
    ER_WRONG_VALUE_COUNT = "ER_WRONG_VALUE_COUNT",
    ER_TOO_LONG_IDENT = "ER_TOO_LONG_IDENT",
    ER_DUP_FIELDNAME = "ER_DUP_FIELDNAME",
    ER_DUP_KEYNAME = "ER_DUP_KEYNAME",
    ER_DUP_ENTRY = "ER_DUP_ENTRY",
    ER_WRONG_FIELD_SPEC = "ER_WRONG_FIELD_SPEC",
    ER_PARSE_ERROR = "ER_PARSE_ERROR",
    ER_EMPTY_QUERY = "ER_EMPTY_QUERY",
    ER_NONUNIQ_TABLE = "ER_NONUNIQ_TABLE",
    ER_INVALID_DEFAULT = "ER_INVALID_DEFAULT",
    ER_MULTIPLE_PRI_KEY = "ER_MULTIPLE_PRI_KEY",
    ER_TOO_MANY_KEYS = "ER_TOO_MANY_KEYS",
    ER_TOO_MANY_KEY_PARTS = "ER_TOO_MANY_KEY_PARTS",
    ER_TOO_LONG_KEY = "ER_TOO_LONG_KEY",
    ER_KEY_COLUMN_DOES_NOT_EXITS = "ER_KEY_COLUMN_DOES_NOT_EXITS",
    ER_BLOB_USED_AS_KEY = "ER_BLOB_USED_AS_KEY",
    ER_TOO_BIG_FIELDLENGTH = "ER_TOO_BIG_FIELDLENGTH",
    ER_WRONG_AUTO_KEY = "ER_WRONG_AUTO_KEY"
  }
  
  export const MySQLErrorMessages: Record<MySQLErrorCodes, string> = {
    [MySQLErrorCodes.CR_UNKNOWN_ERROR]: "Unknown MySQL error",
    [MySQLErrorCodes.CR_SOCKET_CREATE_ERROR]: "Can't create UNIX socket",
    [MySQLErrorCodes.CR_CONNECTION_ERROR]: "Can't connect to local MySQL server through socket",
    [MySQLErrorCodes.CR_CONN_HOST_ERROR]: "Can't connect to MySQL server on specified host",
    [MySQLErrorCodes.CR_IPSOCK_ERROR]: "Can't create TCP/IP socket",
    [MySQLErrorCodes.CR_UNKNOWN_HOST]: "Unknown MySQL server host",
    [MySQLErrorCodes.CR_SERVER_GONE_ERROR]: "MySQL server has gone away",
    [MySQLErrorCodes.CR_VERSION_ERROR]: "Protocol mismatch; server and client version mismatch",
    [MySQLErrorCodes.ER_HASHCHK]: "hashchk",
    [MySQLErrorCodes.ER_NISAMCHK]: "isamchk",
    [MySQLErrorCodes.ER_NO]: "NO",
    [MySQLErrorCodes.ER_YES]: "YES",
    [MySQLErrorCodes.ER_CANT_CREATE_FILE]: "Can't create file",
    [MySQLErrorCodes.ER_CANT_CREATE_TABLE]: "Can't create table",
    [MySQLErrorCodes.ER_CANT_CREATE_DB]: "Can't create database",
    [MySQLErrorCodes.ER_DB_CREATE_EXISTS]: "Can't create database; database exists",
    [MySQLErrorCodes.ER_DB_DROP_EXISTS]: "Can't drop database; database doesn't exist",
    [MySQLErrorCodes.ER_DB_DROP_DELETE]: "Error dropping database; can't delete directory",
    [MySQLErrorCodes.ER_DB_DROP_RMDIR]: "Error dropping database; can't remove directory",
    [MySQLErrorCodes.ER_CANT_DELETE_FILE]: "Error on delete of file",
    [MySQLErrorCodes.ER_CANT_FIND_SYSTEM_REC]: "Can't read record in system table",
    [MySQLErrorCodes.ER_CANT_GET_STAT]: "Can't get status of file",
    [MySQLErrorCodes.ER_CANT_GET_WD]: "Can't get working directory",
    [MySQLErrorCodes.ER_CANT_LOCK]: "Can't lock file",
    [MySQLErrorCodes.ER_CANT_OPEN_FILE]: "Can't open file",
    [MySQLErrorCodes.ER_FILE_NOT_FOUND]: "Can't find file",
    [MySQLErrorCodes.ER_CANT_READ_DIR]: "Can't read directory",
    [MySQLErrorCodes.ER_CANT_SET_WD]: "Can't change directory",
    [MySQLErrorCodes.ER_CHECKREAD]: "Record has changed since last read",
    [MySQLErrorCodes.ER_DISK_FULL]: "Disk full; waiting for someone to free some space",
    [MySQLErrorCodes.ER_DUP_KEY]: "Can't write; duplicate key in table",
    [MySQLErrorCodes.ER_ERROR_ON_CLOSE]: "Error on close of file",
    [MySQLErrorCodes.ER_ERROR_ON_READ]: "Error reading file",
    [MySQLErrorCodes.ER_ERROR_ON_RENAME]: "Error on rename of file",
    [MySQLErrorCodes.ER_ERROR_ON_WRITE]: "Error writing file",
    [MySQLErrorCodes.ER_FILE_USED]: "File is locked against change",
    [MySQLErrorCodes.ER_FILSORT_ABORT]: "Sort aborted",
    [MySQLErrorCodes.ER_FORM_NOT_FOUND]: "View doesn't exist",
    [MySQLErrorCodes.ER_GET_ERRNO]: "Got error from storage engine",
    [MySQLErrorCodes.ER_ILLEGAL_HA]: "Table storage engine doesn't have this option",
    [MySQLErrorCodes.ER_KEY_NOT_FOUND]: "Can't find record in table",
    [MySQLErrorCodes.ER_NOT_FORM_FILE]: "Incorrect information in file",
    [MySQLErrorCodes.ER_NOT_KEYFILE]: "Incorrect key file for table; try to repair it",
    [MySQLErrorCodes.ER_OLD_KEYFILE]: "Old key file for table; repair it",
    [MySQLErrorCodes.ER_OPEN_AS_READONLY]: "Table is read only",
    [MySQLErrorCodes.ER_OUTOFMEMORY]: "Out of memory; restart server and try again",
    [MySQLErrorCodes.ER_OUT_OF_SORTMEMORY]: "Out of sort memory; consider increasing server sort buffer size",
    [MySQLErrorCodes.ER_UNEXPECTED_EOF]: "Unexpected EOF found when reading file",
    [MySQLErrorCodes.ER_CON_COUNT_ERROR]: "Too many connections",
    [MySQLErrorCodes.ER_OUT_OF_RESOURCES]: "Out of resources when opening file",
    [MySQLErrorCodes.ER_BAD_HOST_ERROR]: "Bad host",
    [MySQLErrorCodes.ER_HANDSHAKE_ERROR]: "Bad handshake",
    [MySQLErrorCodes.ER_DBACCESS_DENIED_ERROR]: "Access denied for user to database",
    [MySQLErrorCodes.ER_ACCESS_DENIED_ERROR]: "Access denied for user",
    [MySQLErrorCodes.ER_NO_DB_ERROR]: "No database selected",
    [MySQLErrorCodes.ER_UNKNOWN_COM_ERROR]: "Unknown command",
    [MySQLErrorCodes.ER_BAD_NULL_ERROR]: "Column cannot be null",
    [MySQLErrorCodes.ER_BAD_DB_ERROR]: "Unknown database",
    [MySQLErrorCodes.ER_TABLE_EXISTS_ERROR]: "Table already exists",
    [MySQLErrorCodes.ER_BAD_TABLE_ERROR]: "Unknown table",
    [MySQLErrorCodes.ER_NON_UNIQ_ERROR]: "Column in is ambiguous",
    [MySQLErrorCodes.ER_SERVER_SHUTDOWN]: "Server shutdown in progress",
    [MySQLErrorCodes.ER_BAD_FIELD_ERROR]: "Unknown column",
    [MySQLErrorCodes.ER_WRONG_FIELD_WITH_GROUP]: "Can't group on field",
    [MySQLErrorCodes.ER_WRONG_GROUP_FIELD]: "Can't group on field",
    [MySQLErrorCodes.ER_WRONG_SUM_SELECT]: "Can't use field in a GROUP BY statement",
    [MySQLErrorCodes.ER_WRONG_VALUE_COUNT]: "Column count doesn't match value count",
    [MySQLErrorCodes.ER_TOO_LONG_IDENT]: "Identifier name is too long",
    [MySQLErrorCodes.ER_DUP_FIELDNAME]: "Duplicate column name",
    [MySQLErrorCodes.ER_DUP_KEYNAME]: "Duplicate key name",
    [MySQLErrorCodes.ER_DUP_ENTRY]: "Duplicate entry for key",
    [MySQLErrorCodes.ER_WRONG_FIELD_SPEC]: "Incorrect column specifier for column",
    [MySQLErrorCodes.ER_PARSE_ERROR]: "Syntax error in SQL statement",
    [MySQLErrorCodes.ER_EMPTY_QUERY]: "Query was empty",
    [MySQLErrorCodes.ER_NONUNIQ_TABLE]: "Not unique table/alias",
    [MySQLErrorCodes.ER_INVALID_DEFAULT]: "Invalid default value for column",
    [MySQLErrorCodes.ER_MULTIPLE_PRI_KEY]: "Multiple primary keys defined",
    [MySQLErrorCodes.ER_TOO_MANY_KEYS]: "Too many keys specified",
    [MySQLErrorCodes.ER_TOO_MANY_KEY_PARTS]: "Too many key parts specified",
    [MySQLErrorCodes.ER_TOO_LONG_KEY]: "Specified key was too long",
    [MySQLErrorCodes.ER_KEY_COLUMN_DOES_NOT_EXITS]: "Key column doesn't exist in table",
    [MySQLErrorCodes.ER_BLOB_USED_AS_KEY]: "BLOB column can't be used in key specification",
    [MySQLErrorCodes.ER_TOO_BIG_FIELDLENGTH]: "Column length too big; use BLOB or TEXT instead",
    [MySQLErrorCodes.ER_WRONG_AUTO_KEY]: "Incorrect table definition; only one auto column allowed"
  };
  